### ISSUE TITLE
Bot Offline?

### ISSUE THREAD

**Issue by chrisbarnes2000** [Bo0ne/MinecraftServerDiscordBot#1]
Hi, 

I'm new to using discord bots...
I've downloaded the `config.properties` & `Minecraft.Server.Bot-1.0-all.jar`, 
Setup/added a bot token via [these instructions](https://www.writebots.com/discord-bot-token/),
Then tried to run `java -jar Minecraft.Server.Bot-1.0-all.jar`

and I'm getting an out put of 
[main] INFO net.dv8tion.jda.api.JDA - Login Successful!
[JDA MainWS-WriteThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!

but the bot still seems to be offline... do I add the config and jar to the server folder or run it from my computer?

Thanks for the help, in advance.

**Comment by Bo0ne** [comment]
Hi.
It doesn't matter where you put the files for the bot as long as the .jar
and the properties file is in the same folder.
If you got the JDA finished loading screen it means the bot is connected to
the server and the only reason it can appear offline is because your
minecraft server is offline.
Double check if the ip address to the server is correct in the properties
file and make sure the minecraft server is running.
Cheers

**Comment by Bo0ne** [comment]
The only other issue besides that could be that the minecraft server is not running on the default 25565 port.
I just realized that I have no way to change the port in the bot xD

**Comment by Bo0ne** [comment]
I updated the bot so you can change the Minecraft Server port now as well.

**Comment by chrisbarnes2000** [comment]
Nice catch, It's working now. 👍
